# Generated by Django 4.2.1 on 2023-05-28 13:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='data_entrada',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='visitante',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='hora_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visitante',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
